version: '3.8'

services:
  identity:
    container_name: utube.services.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
    ports:
      - "8080"
      - "8081"
    networks:
      - utube_network
    env_file:
      - ../scripts/secrets/identity-service.env
    volumes:
      - ../scripts/certs:/https:ro


networks:
  utube_network:
    name: my_utube_network
    external: true
