version: '3.8'

services:
  processservice.worker:
    container_name: utube.services.process
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    env_file:
      - ../scripts/secrets/process-service.env
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ../scripts/certs:/https:ro
    networks:
      - utube_network

networks:
  utube_network:
    name: my_utube_network
    external: true