version: '3.8'

services:
  reverseproxy.bff:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    container_name: utube.reverseproxy
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ../scripts/certs:/https:ro
    networks:
      - utube_network

networks:
  utube_network:
    name: my_utube_network
    external: true
