global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'storage-service'
    static_configs:
      - targets: ['storage.service:80']

  - job_name: 'video-service'
    static_configs:
      - targets: ['video.service:80']

  - job_name: 'reverse-proxy'
    static_configs:
      - targets: ['reverseproxy:8080']
