name: Build Reverse Proxy on Pull Request and Push

on:
  push:
    paths: ['reverse-proxy/**', '.github/workflows/reverseproxy**']
  pull_request:
    paths: ['reverse-proxy/**', '.github/workflows/reverseproxy**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Install dependencies
        working-directory: ./reverse-proxy
        run: dotnet restore
      
      - name: Build
        working-directory: ./reverse-proxy
        run: dotnet build --configuration Release --no-restore