name: Build Reverse Proxy on Pull Request and Push

on:
  push:
    paths: ['reverse-proxy/**', '.github/workflows/reverseproxy**']
  pull_request:
    paths: ['reverse-proxy/**', '.github/workflows/reverseproxy**']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/reverse-proxy

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Install dependencies
        working-directory: ./reverse-proxy
        run: |
          dotnet restore StorageService.sln
      
      - name: Build
        working-directory: ./reverse-proxy
        run: dotnet build ReverseProxy.sln --configuration Release --no-restore

  Publish:
    name: Publish to Github Registry
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: reverse-proxy/.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.documentation=https://github.com/${{github.repository}}/blob/dev/reverse-proxy/README.md
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}

