name: Build Web Client on Pull Request and Push

on:
  push:
    paths: ['web-client/**', '.github/workflows/webclient**']
  pull_request:
    paths: ['web-client/**', '.github/workflows/webclient**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node js
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          cache: 'npm'
      
      - name: Install dependencies
        working-directory: ./web-client/utube.web
        run: npm install
      
      - name: Build
        working-directory: ./web-client/utube.web
        run: npm run build